export const ADD_PERSON_REQUEST = "ADD_PERSON_REQUEST";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";

export const FIND_PERSON_REQUEST = "FIND_PERSON_REQUEST";
export const FIND_PERSON_SUCCESS = "FIND_PERSON_SUCCESS";

export const UPDATE_PERSON_REQUEST = "UPDATE_PERSON_REQUEST";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";

export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";