export const ADD_PERSON_REQUEST = "ADD_PERSON_REQUEST";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";

export const FIND_PERSON_REQUEST = "FIND_PERSON_REQUEST";
export const FIND_PERSON_SUCCESS = "FIND_PERSON_SUCCESS";

export const FIND_PERSON_BY_NAME_REQUEST = "FIND_PERSON_BY_NAME_REQUEST";
export const FIND_PERSON_BY_NAME_SUCCESS = "FIND_PERSON_BY_NAME_SUCCESS";

export const FIND_PERSON_SCREEN = "FIND_PERSON_SCREEN";


export const UPDATE_PERSON_REQUEST = "UPDATE_PERSON_REQUEST";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";

export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";

export const ALL_PERSON_REQUEST = "ALL_PERSON_REQUEST";
export const ALL_PERSON_SUCCESS = "ALL_PERSON_SUCCESS";

export const FIND_PERSON_BY_NAME_REQUEST_EDIT = "FIND_PERSON_BY_NAME_REQUEST_EDIT";
export const FIND_PERSON_BY_NAME_SUCCESS_EDIT = "FIND_PERSON_BY_NAME_SUCCESS_EDIT";